version: "3.9"

services:
# MariaDB
 mariadb:
  build: ./reqs/mariadb/
  image: mariadb
  container_name: mariadb
  networks:
   - mynet
  volumes:
   - "/home/asaadi/data/db-data:/var/lib/mysql"
  env_file:
   - ./.env
  command: ./run.sh
  restart: always
# nginx
 nginx:
  build: ./reqs/nginx/
  image: nginx
  container_name: nginx
  ports:
   - "443:443"
  networks:
   - mynet
  volumes:
   - "/home/asaadi/data/wp-data:/www/wordpress"
  command: ./run.sh
  restart: always
# WordPress
 wordpress:
  build: ./reqs/wordpress/
  image: wordpress
  container_name: wordpress
  networks:
   - mynet
  volumes:
   - "/home/asaadi/data/wp-data:/www/wordpress"
  env_file:
   - ./.env
  command: ./run.sh
  restart: always
# redis
 redis:
  build: ./reqs/bonus/redis/
  image: redis
  container_name: redis
  networks:
   - mynet
  command: ./run.sh
  restart: always
# ftp
 ftp:
  build: ./reqs/bonus/ftp/
  image: ftp
  container_name: ftp
  networks:
   - mynet
  command: ./run.sh
  restart: always
  ports:
   - "21:21"
   - "21000:21000"
  env_file:
   - ./.env
# adminer
 adminer:
  build: ./reqs/bonus/adminer/
  image: adminer
  container_name: adminer
  networks:
   - mynet
  ports:
   - "5050:5050"
  restart: always
  command: ./run.sh
# influxdb
 influxdb:
  build: ./reqs/bonus/influxdb/
  image: influxdb
  container_name: influxdb
  ports:
   - "8086:8086"
  restart: always
  command: ./run.sh
  volume:
   - "/home/asaadi/data/influxdb-data:/var/lib/influxdb"
  network:
   - mynet
# grafana

networks:
 mynet: