version: "3.9"

services:
 nginx:
  build: ./nginx/
  ports:
   - "443:443"
  networks:
   - app_default
 wordpress:
  build: ./WordPress+php-fpm/
  networks:
   - app_default
  volumes:
   - "/home/asaadi/data/wp-data:/www/wordpress"
 mariadb:
  build: ./MariaDB/
  networks:
   - app_default
  volumes:
   - "/home/asaadi/data/db-data:/var/lib/mysql"

networks:
 app_default: