version: "3.9"

services:
# MariaDB
 mariadb:
  build: ./reqs/mariadb/
  image: mariadb
  container_name: mariadb
  networks:
   - mynet
  volumes:
   - database_volume:/var/lib/mysql
  env_file:
   - ./.env
  restart: always
# nginx
 nginx:
  build: ./reqs/nginx/
  image: nginx
  container_name: nginx
  ports:
   - "443:443"
  networks:
   - mynet
  volumes:
   - wordpress_volume:/www/wordpress
  restart: always
# WordPress
 wordpress:
  build: ./reqs/wordpress/
  image: wordpress
  container_name: wordpress
  networks:
   - mynet
  volumes:
   - wordpress_volume:/www/wordpress
  env_file:
   - ./.env
  restart: always
# redis
 redis:
  build: ./reqs/bonus/redis/
  image: redis
  container_name: redis
  networks:
   - mynet
  restart: always
# ftp
 ftp:
  build: ./reqs/bonus/ftp/
  image: ftp
  container_name: ftp
  networks:
   - mynet
  restart: always
  ports:
   - "21:21"
   - "21000:21000"
  env_file:
   - ./.env
# adminer
 adminer:
  build: ./reqs/bonus/adminer/
  image: adminer
  container_name: adminer
  networks:
   - mynet
  ports:
   - "5050:5050"
  restart: always
# influxdb
 influxdb:
  build: ./reqs/bonus/influxdb/
  image: influxdb
  container_name: influxdb
  ports:
   - "8086:8086"
  restart: always
  volumes:
   - influxdb_volume:/var/lib/influxdb
  networks:
   - mynet
# grafana
 grafana:
  build: ./reqs/bonus/grafana/
  image: grafana
  container_name: grafana
  restart: always
  networks:
   - mynet
  ports:
   - "3000:3000"
# website
 website:
  build: ./reqs/bonus/website/
  image: website
  container_name: website
  restart: always
  networks:
   - mynet
  ports:
   - "5000:5000"

volumes:
 database_volume:
  driver: local
  driver_opts:
   o: bind
   type: none
   device: /home/asaadi/data/db-data
 wordpress_volume:
  driver: local
  driver_opts:
   o: bind
   type: none
   device: /home/asaadi/data/wp-data
 influxdb_volume:
  driver: local
  driver_opts:
   o: bind
   type: none
   device: /home/asaadi/data/influxdb-data

networks:
 mynet: