version: "3.9"

services:
# MariaDB
 mariadb:
  build: ./reqs/mariadb/
  image: mariadb
  container_name: mariadb
  networks:
   - app_default
  volumes:
   - "/home/asaadi/data/db-data:/var/lib/mysql"
  env_file:
   - ./.env
  command: ./run.sh
  restart: always
# nginx
 nginx:
  build: ./reqs/nginx/
  image: nginx
  container_name: nginx
  ports:
   - "443:443"
  networks:
   - app_default
  volumes:
   - "/home/asaadi/data/wp-data:/www/wordpress"
  command: ./run.sh
  restart: always
# WordPress
 wordpress:
  build: ./reqs/wordpress/
  image: wordpress
  container_name: wordpress
  networks:
   - app_default
  volumes:
   - "/home/asaadi/data/wp-data:/www/wordpress"
  env_file:
   - ./.env
  command: ./run.sh
  restart: always
# redis
 redis:
  build: ./reqs/bonus/redis/
  image: redis
  container_name: redis
  networks:
   - app_default
  volumes:
   - "/home/asaadi/data/wp-data:/www/wordpress"
  command: ./run.sh
  restart: always

networks:
 app_default: