version: "3.9"

services:
 mariadb:
  build: ./reqs/mariadb/
  image: mariadb
  container_name: mariadb
  networks:
   - app_default
  volumes:
   - "/home/asaadi/data/db-data:/var/lib/mysql"
  env_file:
   - .env
 nginx:
  build: ./reqs/nginx/
  image: nginx
  container_name: nginx
  ports:
   - "443:443"
  networks:
   - app_default
  volumes:
   - "/home/asaadi/data/wp-data:/www/wordpress"
 wordpress:
  build: ./reqs/wordpress/
  image: wordpress
  container_name: wordpress
  networks:
   - app_default
  env_file:
   - .env
  volumes:
   - "/home/asaadi/data/wp-data:/www/wordpress"

networks:
 app_default: